### ISSUE TITLE
output.mp4 is Corrupt

### ISSUE THREAD

**Issue by iamDyeus** [zackmawaldi/YouTube-shorts-generator#16]
in the temp_clips folder, the output.mp4 video file is Corrupt and doesn't work.

**Comment by zackmawaldi** [comment]
Super weird. Does the code output normally (doesn't crash)? Might be an issue with the [redvid](https://github.com/elmoiv/redvid) library, which is the one that does the downloading. Also, I updated the repo since your issue, so if you'd like, try again with the updated code. (and also sorry for late reply!)
