### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by manashan** [zackmawaldi/YouTube-shorts-generator#3]
how can I fix this issue? It doesn't let me go further.
![Screenshot_2](https://user-images.githubusercontent.com/67643821/165001474-03973540-4731-4370-904a-bda23a325629.jpg)

**Comment by zackmawaldi** [comment]
There were syntax errors in `config.py` file that weren't caught, thanks for highlighting the errors! I updated the file. Try using the updated [config.py](https://github.com/zackmawaldi/YouTube-shorts-generator/blob/main/config.py) code and let me know if the issue persists.

Zack

**Comment by manashan** [comment]
@zackmawaldi thank you Zach. I tried to run but getting this rn. What should I do here
![Screenshot_3](https://user-images.githubusercontent.com/67643821/165013403-74e64267-c761-40fb-a6a9-614ef0844889.jpg)
?

**Comment by zackmawaldi** [comment]
The error is a key-value error, which means the code tried to access a key that doesn't exist.

The way config file works is through series of dictionaries with key-value pairs. Example:

_config.py_
`login_info = { 'username': 'jake', 'password': '1234'}`

If username needs to be accessed, `config.login_info['username']` returns --> `'jake'`
But if a key was entered that isn't there, it returns a KeyError. Such as if we try to access `age`.
Ex: `config.login_info['age']` --> `KeyError` since 'age' isn't in `login_info`

---

My hunch is that line 18 in `reddit_scraper.py` was modified from the [original](https://github.com/zackmawaldi/YouTube-shorts-generator/blob/main/reddit_scraper.py):
`    red = praw.Reddit(client_id=config.reddit_login['client_id'],`

to

`    red = praw.Reddit(client_id=config.reddit_login['ACTUAL ID'],`


If I'm correct, try changing it back. Let me know if that does it.
Zack

**Comment by zackmawaldi** [comment]
Can you send me a screenshot or the code to your `reddit_scraper.py` file?

**Comment by zackmawaldi** [comment]
Ah, guessed it!

Change lines 18-22 exactly as seen in original [reddit_scraper.py](https://github.com/zackmawaldi/YouTube-shorts-generator/blob/main/reddit_scraper.py) file. Let me know if that changes things.

**Comment by manashan** [comment]
Thank you Zach. I finally managed the Reddit part. But I occur another problem here. What would be the issue here?
![Screenshot_5](https://user-images.githubusercontent.com/67643821/165136913-1a1ec076-1e89-44f5-a618-95c2dc5ddd85.jpg)

**Comment by zackmawaldi** [comment]
This is permission error. It was encountered in #2 . Check the solution mentioned there, and lmk.

**Comment by manashan** [comment]
> This is permission error. It was encountered in #2 . Check the solution mentioned there, and lmk.

what about this one?sorry I know you have finals, I bother you a lot.
![Screenshot_4](https://user-images.githubusercontent.com/67643821/165140027-1246c340-fe13-4048-8377-e9f717508556.jpg)

**Comment by zackmawaldi** [comment]
Seems like a problem `redvid`. First line of error says `'ffmpeg' is not recognized`. Do you have `ffmpeg` installed? Try following a YouTube tutorial on it.

**Comment by manashan** [comment]
> Seems like a problem `redvid`. First line of error says `'ffmpeg' is not recognized`. Do you have `ffmpeg` installed? Try following a YouTube tutorial on it.

I think it's the issue with permission because script tries to change the file name I guess. I will try to make it start tonight. Thanks for your help.
